### ISSUE TITLE
Compression checklist

### ISSUE THREAD

**Issue by nebfield** [PGScatalog/pgsc_calc#47]
The workflow makes some intermediate plain text files in the work directory that should be compressed by default because they can get very big (#43).

- [X] Matching log (`pgscatalog_utils v0.1.2`)
- [x] Combined scorefiles downloaded from the PGS Catalog 
- [x] Matched scorefile output (.scorefile)
- [x] Relabelled variant information files (zst)
- [x] Calculated .sscores (zstd)
- [x] Aggregated scores (gzip) 

Input files are a bit more complex and we should auto-detect compressed data (zst suffix?):

- [x] plink2 pvar.zst
- [x] plink1 bim.zst

**Comment by nebfield** [comment]
https://github.com/PGScatalog/pgsc_calc/releases/tag/v1.2.0
